### ISSUE TITLE
Ditch codecov in favor of code coverage reporting that works

### ISSUE THREAD

**Issue by jeff-cohere** [kbase/dts#60]
I'm getting tired of rerunning builds because of code coverage report upload failures, so I'm looking at alternatives:

* https://hynek.me/articles/ditch-codecov-python/
* https://github.com/ewjoachim/coverage-comment-action
* https://nedbatchelder.com/blog/202209/making_a_coverage_badge.html

**Comment by jeff-cohere** [comment]
Bumping to v4 of the action and making CI indifferent to the upload/reporting process fixes this for now.

**Comment by bio-boris** [comment]
@jeff-cohere codecov does have some issues, but we found they go away when you add a token. 
![image](https://github.com/kbase/dts/assets/1258634/0510deb6-9e4c-4cfd-ad0c-a639ebfc333c)

**Comment by jeff-cohere** [comment]
Thanks, @bio-boris .
